[package]
name = "shrinking_squares"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
imageproc = "0.23.0"
palette = "0.6.1"
rand = "0.8.5"
conv = "0.3.3"
